### ISSUE TITLE
Error for Packages without a URL

### ISSUE THREAD

**Issue by eugene100hickey** [luisDVA/hexsession#1]
Some packages don't have URL's in their package description. This leads to an error in make_tile(), it comes back with an error in strsplit(). This could be remedied by adding a line `allurls <- allurls[!is.na(allurls)]`between lines 37 and 38 of the pkgurls() function within the helper.R file.

One example of this is the `words` package. (https://cran.r-project.org/web/packages/words/index.html).

There's probably a way to do this more gracefully.

Love the package by the way, really elegant.

**Comment by luisDVA** [comment]
thanks for the heads up!
I did not expect packages to not have anything in the URL field. 
 [a9171fb](https://github.com/luisDVA/hexsession/commit/a9171fb21565141a3e6802b1e402fca00f34692d) fixes this issue, and because packages may not be from CRAN, the simple solution was to make the image in the hex tile non-clickable. 
thanks again

**Comment by eugene100hickey** [comment]
Thanks Luis. I can confirm that this works perfectly for me now.

Again, awesome package.
